apiVersion: devsecops.licenta.ro/v1
kind: ZeroTrustApplication
metadata:
  name: analytics-worker
  namespace: default
spec:
  image: ghcr.io/sabinghost19/analytics-worker@sha256:78df332faad52d2a82eee0272bdc4038b8301fde9d42d032a3ba5c60817f9bca
  replicas: 2
  # Strict SCA → onVulnerabilityFound=Kill → Failed_SupplyChain.
  # Worker include cryptography==41.0.0 cu CVE-uri fixable cunoscute.
  securityPolicyRef:
    name: analytics-strict-policy
  networkZeroTrust:
    egressAllowedTo:
      - namespace: kafka
        ports: [9092]
  runtimeSecurity:
    allowedPaths:
      - /tmp
      - /var/run
    onCompromise: Isolate
