apiVersion: devsecops.licenta.ro/v1
kind: ZeroTrustApplication
metadata:
  name: analytics-worker
  namespace: default
spec:
  image: ghcr.io/sabinghost19/analytics-worker@sha256:1657a765aa7b8c12c24c37d0ce7f2a881f65d6b0a413ffe334c2a576e7b672f6
  replicas: 2
  # Strict SCA → onVulnerabilityFound=Kill → Failed_SupplyChain.
  # Worker include cryptography==41.0.0 cu CVE-uri fixable cunoscute.
  securityPolicyRef:
    name: analytics-strict-policy
  networkZeroTrust:
    egressAllowedTo:
      - namespace: kafka
        ports: [9092]
  runtimeSecurity:
    allowedPaths:
      - /tmp
      - /var/run
    onCompromise: Isolate
