apiVersion: devsecops.licenta.ro/v1
kind: ZeroTrustApplication
metadata:
  name: analytics-worker
  namespace: default
spec:
  image: ghcr.io/sabinghost19/analytics-worker@sha256:73a3b108ba8d7413e6f2162cc26130d7b729ed5dd138f673e495d67fd37daab7
  replicas: 2
  # Strict SCA → onVulnerabilityFound=Kill → Failed_SupplyChain.
  # Worker include cryptography==41.0.0 cu CVE-uri fixable cunoscute.
  securityPolicyRef:
    name: analytics-strict-policy
  networkZeroTrust:
    egressAllowedTo:
      - namespace: kafka
        ports: [9092]
  runtimeSecurity:
    allowedPaths:
      - /tmp
      - /var/run
    onCompromise: Isolate
