apiVersion: devsecops.licenta.ro/v1
kind: ZeroTrustApplication
metadata:
  name: analytics-api
  namespace: default
spec:
  image: ghcr.io/sabinghost19/analytics-api@sha256:67c4847afb91cb84f84a7c1b15752da79fc4ec01303bc77401fbb901d616c822
  replicas: 2
  securityPolicyRef:
    name: analytics-relaxed-policy
  networkZeroTrust:
    ingressAllowedFrom:
      - namespace: api-gateway
    egressAllowedTo:
      - namespace: kafka
        ports: [9092]
  runtimeSecurity:
    allowedPaths:
      - /tmp
      - /var/run
      - /app/cache
    onCompromise: Isolate
