apiVersion: devsecops.licenta.ro/v1
kind: ZeroTrustApplication
metadata:
  name: analytics-api
  namespace: default
spec:
  image: ghcr.io/sabinghost19/analytics-api@sha256:a06c57d8f590cc2ce3fae43d7e7d767e845fac0832f0037ab33f9a38e29df01c
  replicas: 2
  securityPolicyRef:
    name: analytics-relaxed-policy
  networkZeroTrust:
    ingressAllowedFrom:
      - namespace: api-gateway
    egressAllowedTo:
      - namespace: kafka
        ports: [9092]
  runtimeSecurity:
    allowedPaths:
      - /tmp
      - /var/run
      - /app/cache
    onCompromise: Isolate
