apiVersion: devsecops.licenta.ro/v1
kind: ZeroTrustApplication
metadata:
  name: analytics-api
  namespace: default
spec:
  image: ghcr.io/sabinghost19/analytics-api@sha256:71aeb15b95d24c962c008fff3ca148fe8068bf9c1920732fa6a939c84c20b5cc
  replicas: 2
  securityPolicyRef:
    name: analytics-relaxed-policy
  networkZeroTrust:
    ingressAllowedFrom:
      - namespace: api-gateway
    egressAllowedTo:
      - namespace: kafka
        ports: [9092]
  runtimeSecurity:
    allowedPaths:
      - /tmp
      - /var/run
      - /app/cache
    onCompromise: Isolate
