apiVersion: devsecops.licenta.ro/v1
kind: ZeroTrustApplication
metadata:
  name: demo-api
  namespace: default
spec:
  image: ghcr.io/sabinghost19/demo-vulnerable-fastapi@sha256:9bda6f6f0e10776b489ee84a1a662116a2052890a7b415025b7f7abb95b235d2
  replicas: 2
  securityPolicyRef:
    name: demo-app-security-policy
  networkZeroTrust:
    ingressAllowedFrom:
      - namespace: api-gateway
    egressAllowedTo:
      - namespace: database
        ports: [5432]
