apiVersion: devsecops.licenta.ro/v1
kind: ZeroTrustApplication
metadata:
  name: demo-api
  namespace: default
spec:
  image: ""
  replicas: 2
  securityPolicyRef:
    name: demo-app-security-policy
  networkZeroTrust:
    ingressAllowedFrom:
      - namespace: api-gateway
    egressAllowedTo:
      - namespace: database
        ports: [5432]
