apiVersion: devsecops.licenta.ro/v1
kind: ZeroTrustApplication
metadata:
  name: payments-api
  namespace: default
spec:
  # Replaced by the bump-manifests CI job after each pipeline run.
  image: ghcr.io/sabinghost19/payments-api@sha256:970ec06d89496bae1076f0c524ae30071adf33d4d6aa7ed43529232e61bfa51a
  replicas: 2
  securityPolicyRef:
    name: payments-strict-policy
  networkZeroTrust:
    ingressAllowedFrom:
      - namespace: api-gateway
    egressAllowedTo:
      - namespace: database
        ports: [5432]
  runtimeSecurity:
    allowedPaths:
      - /tmp
      - /var/run
    onCompromise: Isolate
