apiVersion: devsecops.licenta.ro/v1
kind: ZeroTrustApplication
metadata:
  name: payments-worker
  namespace: default
spec:
  image: ghcr.io/sabinghost19/payments-worker@sha256:3dd87a5c0b46021f5fabca34df4628ed7c6d8bf7265020004fc555091e250078
  replicas: 2
  securityPolicyRef:
    name: payments-strict-policy
  networkZeroTrust:
    # Worker has no inbound; only outbound to DB + message queue.
    egressAllowedTo:
      - namespace: database
        ports: [5432]
      - namespace: kafka
        ports: [9092]
  runtimeSecurity:
    allowedPaths:
      - /tmp
      - /var/run
    onCompromise: Isolate
