apiVersion: devsecops.licenta.ro/v1
kind: ZeroTrustApplication
metadata:
  name: payments-worker
  namespace: default
spec:
  image: ghcr.io/sabinghost19/payments-worker@sha256:cea19d9043d423e9a1ae832bfe619df9d620f7d950ee7d160f3dbab685bf42f0
  replicas: 2
  securityPolicyRef:
    name: payments-strict-policy
  networkZeroTrust:
    # Worker has no inbound; only outbound to DB + message queue.
    egressAllowedTo:
      - namespace: database
        ports: [5432]
      - namespace: kafka
        ports: [9092]
  runtimeSecurity:
    allowedPaths:
      - /tmp
      - /var/run
    onCompromise: Isolate
