apiVersion: devsecops.licenta.ro/v1
kind: ZeroTrustApplication
metadata:
  name: payments-worker
  namespace: default
spec:
  image: ghcr.io/sabinghost19/payments-worker@sha256:dff1cefd8652a849fe3de5377ced2089aa805d23b5223bca9dbf5225d8eafe4d
  replicas: 2
  securityPolicyRef:
    name: payments-strict-policy
  networkZeroTrust:
    # Worker has no inbound; only outbound to DB + message queue.
    egressAllowedTo:
      - namespace: database
        ports: [5432]
      - namespace: kafka
        ports: [9092]
  runtimeSecurity:
    allowedPaths:
      - /tmp
      - /var/run
    onCompromise: Isolate
